/**
 * Bundled offline food-database subset (USDA FoodData Central / SR Legacy
 * household-serving figures, dietary fiber rounded to 1 decimal).
 *
 * This backs the "Database search" lane: generics and produce that aren't in
 * the user's library yet show up under search results, and picking one copies
 * it into her library (source: 'usda') before it's added to the day — fully
 * offline, entered once, reused forever.
 *
 * Names deliberately avoid duplicating SEED_FOODS staples; overlap is also
 * filtered out at runtime against whatever is in the library.
 */

export interface UsdaFood {
  name: string;
  servingLabel: string;
  fiberPerServing: number;
}

export const USDA_FOODS: UsdaFood[] = [
  // ------------------------------------------------------------- fruit
  { name: 'Apricot', servingLabel: '1 fruit', fiberPerServing: 0.7 },
  { name: 'Apricots, dried', servingLabel: '1/4 cup', fiberPerServing: 2.4 },
  { name: 'Cherries, sweet', servingLabel: '1 cup, pitted', fiberPerServing: 3.2 },
  { name: 'Grapefruit', servingLabel: '1/2 medium', fiberPerServing: 2.0 },
  { name: 'Grapes', servingLabel: '1 cup', fiberPerServing: 0.8 },
  { name: 'Peach', servingLabel: '1 medium', fiberPerServing: 2.3 },
  { name: 'Nectarine', servingLabel: '1 medium', fiberPerServing: 2.4 },
  { name: 'Plum', servingLabel: '1 fruit', fiberPerServing: 0.9 },
  { name: 'Pineapple', servingLabel: '1 cup, chunks', fiberPerServing: 2.3 },
  { name: 'Watermelon', servingLabel: '1 cup, diced', fiberPerServing: 0.6 },
  { name: 'Cantaloupe', servingLabel: '1 cup, cubed', fiberPerServing: 1.4 },
  { name: 'Honeydew melon', servingLabel: '1 cup, cubed', fiberPerServing: 1.4 },
  { name: 'Pomegranate arils', servingLabel: '1/2 cup', fiberPerServing: 3.5 },
  { name: 'Papaya', servingLabel: '1 cup, cubed', fiberPerServing: 2.5 },
  { name: 'Guava', servingLabel: '1 fruit', fiberPerServing: 3.0 },
  { name: 'Persimmon', servingLabel: '1 fruit', fiberPerServing: 6.0 },
  { name: 'Passion fruit', servingLabel: '2 fruits', fiberPerServing: 3.8 },
  { name: 'Tangerine', servingLabel: '1 medium', fiberPerServing: 1.6 },
  { name: 'Clementine', servingLabel: '1 fruit', fiberPerServing: 1.3 },
  { name: 'Cranberries, raw', servingLabel: '1 cup, whole', fiberPerServing: 3.6 },
  { name: 'Cranberries, dried', servingLabel: '1/4 cup', fiberPerServing: 1.8 },
  { name: 'Raisins', servingLabel: '1/4 cup', fiberPerServing: 1.6 },
  { name: 'Currants, dried', servingLabel: '1/4 cup', fiberPerServing: 2.4 },
  { name: 'Applesauce, unsweetened', servingLabel: '1/2 cup', fiberPerServing: 1.3 },
  { name: 'Boysenberries, frozen', servingLabel: '1 cup', fiberPerServing: 7.0 },
  { name: 'Gooseberries', servingLabel: '1 cup', fiberPerServing: 6.5 },
  { name: 'Elderberries', servingLabel: '1 cup', fiberPerServing: 10.2 },
  { name: 'Coconut, shredded, unsweetened', servingLabel: '1/4 cup', fiberPerServing: 3.3 },
  { name: 'Fruit cocktail, canned in juice', servingLabel: '1/2 cup', fiberPerServing: 1.2 },
  { name: 'Starfruit', servingLabel: '1 medium', fiberPerServing: 2.5 },
  { name: 'Plantain, cooked', servingLabel: '1/2 cup, slices', fiberPerServing: 1.8 },

  // -------------------------------------------------------- vegetables
  { name: 'Parsnip, cooked', servingLabel: '1/2 cup, slices', fiberPerServing: 2.8 },
  { name: 'Turnip, cooked', servingLabel: '1/2 cup, cubed', fiberPerServing: 1.6 },
  { name: 'Rutabaga, cooked', servingLabel: '1/2 cup, cubed', fiberPerServing: 1.6 },
  { name: 'Beets, cooked', servingLabel: '1/2 cup, slices', fiberPerServing: 1.7 },
  { name: 'Kale, cooked', servingLabel: '1 cup, chopped', fiberPerServing: 2.6 },
  { name: 'Collard greens, cooked', servingLabel: '1/2 cup', fiberPerServing: 3.8 },
  { name: 'Swiss chard, cooked', servingLabel: '1 cup', fiberPerServing: 3.7 },
  { name: 'Mustard greens, cooked', servingLabel: '1/2 cup', fiberPerServing: 1.4 },
  { name: 'Beet greens, cooked', servingLabel: '1/2 cup', fiberPerServing: 2.1 },
  { name: 'Okra, cooked', servingLabel: '1/2 cup', fiberPerServing: 2.0 },
  { name: 'Eggplant, cooked', servingLabel: '1 cup, cubed', fiberPerServing: 2.5 },
  { name: 'Zucchini, cooked', servingLabel: '1 cup, sliced', fiberPerServing: 1.8 },
  { name: 'Summer squash, raw', servingLabel: '1 cup, sliced', fiberPerServing: 1.2 },
  { name: 'Acorn squash, baked', servingLabel: '1/2 cup, cubed', fiberPerServing: 4.5 },
  { name: 'Spaghetti squash, cooked', servingLabel: '1 cup', fiberPerServing: 2.2 },
  { name: 'Pumpkin, canned', servingLabel: '1/2 cup', fiberPerServing: 3.6 },
  { name: 'Asparagus, cooked', servingLabel: '6 spears', fiberPerServing: 1.8 },
  { name: 'Cabbage, cooked', servingLabel: '1/2 cup, shredded', fiberPerServing: 1.4 },
  { name: 'Red cabbage, raw', servingLabel: '1 cup, shredded', fiberPerServing: 1.5 },
  { name: 'Bok choy, cooked', servingLabel: '1 cup, shredded', fiberPerServing: 1.7 },
  { name: 'Celery', servingLabel: '2 stalks', fiberPerServing: 1.2 },
  { name: 'Cucumber, with peel', servingLabel: '1 cup, sliced', fiberPerServing: 0.8 },
  { name: 'Bell pepper, raw', servingLabel: '1 medium', fiberPerServing: 2.5 },
  { name: 'Tomato, raw', servingLabel: '1 medium', fiberPerServing: 1.5 },
  { name: 'Cherry tomatoes', servingLabel: '1 cup', fiberPerServing: 1.8 },
  { name: 'Tomato sauce, canned', servingLabel: '1/2 cup', fiberPerServing: 1.8 },
  { name: 'Tomato paste', servingLabel: '2 tbsp', fiberPerServing: 1.3 },
  { name: 'Salsa', servingLabel: '1/4 cup', fiberPerServing: 0.9 },
  { name: 'Mushrooms, cooked', servingLabel: '1/2 cup, sliced', fiberPerServing: 1.7 },
  { name: 'Mushrooms, raw', servingLabel: '1 cup, sliced', fiberPerServing: 0.7 },
  { name: 'Onion, raw', servingLabel: '1/2 cup, chopped', fiberPerServing: 1.4 },
  { name: 'Radishes', servingLabel: '1 cup, sliced', fiberPerServing: 1.9 },
  { name: 'Jicama, raw', servingLabel: '1 cup, sliced', fiberPerServing: 5.9 },
  { name: 'Kohlrabi, raw', servingLabel: '1 cup, sliced', fiberPerServing: 4.9 },
  { name: 'Fennel bulb, raw', servingLabel: '1 cup, sliced', fiberPerServing: 2.7 },
  { name: 'Snow peas, cooked', servingLabel: '1/2 cup', fiberPerServing: 2.2 },
  { name: 'Romaine lettuce', servingLabel: '2 cups, shredded', fiberPerServing: 2.0 },
  { name: 'Spinach, raw', servingLabel: '2 cups', fiberPerServing: 1.4 },
  { name: 'Broccoli, raw', servingLabel: '1 cup, chopped', fiberPerServing: 2.4 },
  { name: 'Cauliflower, raw', servingLabel: '1 cup, chopped', fiberPerServing: 2.1 },
  { name: 'Carrots, cooked', servingLabel: '1/2 cup, slices', fiberPerServing: 2.3 },
  { name: 'Baby carrots', servingLabel: '10 carrots', fiberPerServing: 2.9 },
  { name: 'Hearts of palm, canned', servingLabel: '1/2 cup', fiberPerServing: 1.8 },
  { name: 'Water chestnuts, canned', servingLabel: '1/2 cup, sliced', fiberPerServing: 1.8 },
  { name: 'Yam, cooked', servingLabel: '1/2 cup, cubed', fiberPerServing: 2.7 },
  { name: 'Mixed vegetables, frozen, cooked', servingLabel: '1/2 cup', fiberPerServing: 2.7 },
  { name: 'Sauerkraut, canned', servingLabel: '1/2 cup', fiberPerServing: 2.1 },
  { name: 'Leeks, cooked', servingLabel: '1/2 cup', fiberPerServing: 0.5 },

  // ----------------------------------------------------------- legumes
  { name: 'Great northern beans, cooked', servingLabel: '1/2 cup', fiberPerServing: 6.2 },
  { name: 'Lima beans, cooked', servingLabel: '1/2 cup', fiberPerServing: 6.6 },
  { name: 'Cannellini beans, canned', servingLabel: '1/2 cup', fiberPerServing: 5.7 },
  { name: 'Fava beans, cooked', servingLabel: '1/2 cup', fiberPerServing: 4.6 },
  { name: 'Mung beans, cooked', servingLabel: '1/2 cup', fiberPerServing: 7.7 },
  { name: 'Adzuki beans, cooked', servingLabel: '1/2 cup', fiberPerServing: 8.4 },
  { name: 'Black-eyed peas, cooked', servingLabel: '1/2 cup', fiberPerServing: 5.6 },
  { name: 'Soybeans, cooked', servingLabel: '1/2 cup', fiberPerServing: 5.2 },
  { name: 'Refried beans, canned', servingLabel: '1/2 cup', fiberPerServing: 5.2 },
  { name: 'Chickpeas, canned', servingLabel: '1/2 cup', fiberPerServing: 5.3 },
  { name: 'Green lentils, sprouted, raw', servingLabel: '1/2 cup', fiberPerServing: 3.4 },
  { name: 'Edamame, in pods', servingLabel: '1 cup pods', fiberPerServing: 4.0 },

  // ---------------------------------------------------- grains & breads
  { name: 'White rice, cooked', servingLabel: '1 cup', fiberPerServing: 0.6 },
  { name: 'Wild rice, cooked', servingLabel: '1 cup', fiberPerServing: 3.0 },
  { name: 'Farro, cooked', servingLabel: '1 cup', fiberPerServing: 5.0 },
  { name: 'Millet, cooked', servingLabel: '1 cup', fiberPerServing: 2.3 },
  { name: 'Buckwheat groats, cooked', servingLabel: '1 cup', fiberPerServing: 4.5 },
  { name: 'Amaranth, cooked', servingLabel: '1 cup', fiberPerServing: 5.2 },
  { name: 'Teff, cooked', servingLabel: '1 cup', fiberPerServing: 7.1 },
  { name: 'Couscous, cooked', servingLabel: '1 cup', fiberPerServing: 2.2 },
  { name: 'Rye bread', servingLabel: '1 slice', fiberPerServing: 1.9 },
  { name: 'Pumpernickel bread', servingLabel: '1 slice', fiberPerServing: 2.1 },
  { name: 'Multigrain bread', servingLabel: '1 slice', fiberPerServing: 1.9 },
  { name: 'Sourdough bread', servingLabel: '1 slice', fiberPerServing: 1.0 },
  { name: 'Whole-wheat pita', servingLabel: '1 pita (6.5 in)', fiberPerServing: 4.7 },
  { name: 'Whole-wheat tortilla', servingLabel: '1 tortilla (8 in)', fiberPerServing: 3.0 },
  { name: 'Oat bran, cooked', servingLabel: '1/2 cup', fiberPerServing: 2.9 },
  { name: 'Wheat bran', servingLabel: '1/4 cup', fiberPerServing: 6.2 },
  { name: 'Wheat germ', servingLabel: '2 tbsp', fiberPerServing: 1.9 },
  { name: 'Shredded wheat cereal', servingLabel: '2 biscuits', fiberPerServing: 6.1 },
  { name: 'Raisin bran cereal', servingLabel: '1 cup', fiberPerServing: 7.0 },
  { name: 'Toasted oat O’s cereal', servingLabel: '1 cup', fiberPerServing: 2.8 },
  { name: 'Muesli', servingLabel: '1/2 cup', fiberPerServing: 4.0 },
  { name: 'Granola', servingLabel: '1/2 cup', fiberPerServing: 3.0 },
  { name: 'Instant oatmeal, plain, cooked', servingLabel: '1 packet', fiberPerServing: 2.8 },
  { name: 'Steel-cut oats, dry', servingLabel: '1/4 cup', fiberPerServing: 4.0 },
  { name: 'Rice cakes, brown rice', servingLabel: '2 cakes', fiberPerServing: 0.8 },
  { name: 'Whole-grain wheat crackers', servingLabel: '6 crackers', fiberPerServing: 3.0 },
  { name: 'Rye crispbread', servingLabel: '2 crackers', fiberPerServing: 3.4 },
  { name: 'Whole-wheat flour', servingLabel: '1/4 cup', fiberPerServing: 3.9 },
  { name: 'White spaghetti, cooked', servingLabel: '1 cup', fiberPerServing: 2.5 },
  { name: 'Chickpea pasta, cooked', servingLabel: '2 oz dry', fiberPerServing: 5.0 },

  // ------------------------------------------------------- nuts & seeds
  { name: 'Peanuts', servingLabel: '1 oz', fiberPerServing: 2.4 },
  { name: 'Cashews', servingLabel: '1 oz (18 nuts)', fiberPerServing: 0.9 },
  { name: 'Pecans', servingLabel: '1 oz (19 halves)', fiberPerServing: 2.7 },
  { name: 'Hazelnuts', servingLabel: '1 oz (21 nuts)', fiberPerServing: 2.7 },
  { name: 'Macadamia nuts', servingLabel: '1 oz (10-12 nuts)', fiberPerServing: 2.4 },
  { name: 'Brazil nuts', servingLabel: '1 oz (6 nuts)', fiberPerServing: 2.1 },
  { name: 'Pine nuts', servingLabel: '1 oz', fiberPerServing: 1.0 },
  { name: 'Almond butter', servingLabel: '2 tbsp', fiberPerServing: 3.3 },
  { name: 'Tahini', servingLabel: '2 tbsp', fiberPerServing: 2.8 },
  { name: 'Hemp seeds', servingLabel: '3 tbsp', fiberPerServing: 1.2 },
  { name: 'Sesame seeds', servingLabel: '1 tbsp', fiberPerServing: 1.1 },
  { name: 'Coconut flour', servingLabel: '2 tbsp', fiberPerServing: 5.0 },
  { name: 'Almond flour', servingLabel: '1/4 cup', fiberPerServing: 3.0 },

  // ------------------------------------------------------------ snacks
  { name: 'Dark chocolate, 70-85%', servingLabel: '1 oz', fiberPerServing: 3.1 },
  { name: 'Cocoa powder, unsweetened', servingLabel: '2 tbsp', fiberPerServing: 3.6 },
  { name: 'Tortilla chips', servingLabel: '1 oz', fiberPerServing: 1.2 },
  { name: 'Guacamole', servingLabel: '1/4 cup', fiberPerServing: 2.6 },
  { name: 'Nutritional yeast', servingLabel: '2 tbsp', fiberPerServing: 2.0 },
  { name: 'Trail mix', servingLabel: '1/4 cup', fiberPerServing: 1.5 },
];
